<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom_sex</name>
   <tag></tag>
   <elementGuidId>528a2fff-7e61-4548-a225-e2cc4f0f8b97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_0_6_ZY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='u_0_6_ZY']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'radio' and @class = '_8esa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63ada24e-479b-40ac-a23a-5a6eca10affa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>946e3c0c-98da-455e-84e4-453197bc7fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_8esa</value>
      <webElementGuid>2eb30074-3471-464c-914f-cc838e4288cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sex</value>
      <webElementGuid>b2e8def0-1921-4673-b4b2-4a936e7386d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9e666afb-f3d5-45f5-8fd2-7e5c5450e379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_6_ZY</value>
      <webElementGuid>6f836723-7a8d-4628-a272-7865c376f4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_6_ZY&quot;)</value>
      <webElementGuid>fc425a63-82a4-43c8-9fe6-1974a006dcb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='u_0_6_ZY']</value>
      <webElementGuid>981b776d-b430-46e1-ba08-90187e205fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_0_o_CO']/span[3]/input</value>
      <webElementGuid>ada7e461-0ef6-478f-adda-12036d002107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/input</value>
      <webElementGuid>e057c440-8711-4677-9f36-85fec262157f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'sex' and @id = 'u_0_6_ZY']</value>
      <webElementGuid>5fb9eed5-f912-4bed-af69-eacf470466dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
