<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(We couldn, , t create your acc_7f0a99_1</name>
   <tag></tag>
   <elementGuidId>2f31bc7c-26cd-4459-93d5-ff426d8e7905</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_step_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_step_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f9caef5-58c4-45d1-b058-34fdbfedb82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>53aafeeb-a330-499a-90c4-9f576149099a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _58mg _5dba _2ph-</value>
      <webElementGuid>b0f84edf-d4bc-464f-8f90-09a8111b0399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b8e733a7-92f4-4eab-8f60-d8d1f9ad47d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>a0618dca-468a-4e26-a4a8-fd627c425083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reg_passwd__</value>
      <webElementGuid>d51a1170-61b3-460d-bb00-4fabca0a1161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_step_input</value>
      <webElementGuid>441700f6-457c-4c36-a4c0-589cad0150fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60e9833c-0f39-4688-aa62-47ff965fb422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>New password</value>
      <webElementGuid>682d85d1-f9e1-48cd-8033-8f351ccec70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_step_input&quot;)</value>
      <webElementGuid>f24ca6b5-9baa-461a-bd53-381789b49441</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_step_input']</value>
      <webElementGuid>9912fc58-d73c-434d-83c5-43fdb4e581e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_k_2j']/div/input</value>
      <webElementGuid>0066a4ea-af4f-43d4-97e3-7118f148cce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>4fcb310c-b4e8-439b-a89b-36d9a0f8fdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'reg_passwd__' and @id = 'password_step_input']</value>
      <webElementGuid>197af3b7-d0cd-4cfb-8ca0-304cb7d2ee81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
