<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Male</name>
   <tag></tag>
   <elementGuidId>8592c627-b4ca-46b4-83c0-e9240f1cb8f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='u_0_o_CF']/span[2]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[(text() = 'Male' or . = 'Male')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bcda419c-b076-4ee2-9eb9-33b2a85600bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_58mt</value>
      <webElementGuid>21b64a6c-ac0e-4ee1-9439-fa9ec86b0f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>u_0_5_7b</value>
      <webElementGuid>d131797b-3d30-459e-be9e-2619748ead84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>fc802cfe-cd82-483c-8c57-b649e93742a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_o_CF&quot;)/span[@class=&quot;_5k_2 _5dba&quot;]/label[@class=&quot;_58mt&quot;]</value>
      <webElementGuid>1f44bc68-9f3b-4449-8b1a-e0d2cd5d2f86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_0_o_CF']/span[2]/label</value>
      <webElementGuid>30551b4f-ac22-4094-939f-a85a8ad68f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/following::label[1]</value>
      <webElementGuid>18c76e46-064c-407e-b797-8d2da4bb1d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::label[2]</value>
      <webElementGuid>094ac84c-493f-41b2-8af8-1517d0760157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom'])[1]/preceding::label[1]</value>
      <webElementGuid>40681d47-9564-4896-b0f8-811aa5154332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your pronoun is visible to everyone.'])[1]/preceding::label[2]</value>
      <webElementGuid>e645de1a-ced8-4ebd-9d3e-5f584dfc156d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Male']/parent::*</value>
      <webElementGuid>737a26b7-cddf-49c1-a239-c42d3bf5d449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/label</value>
      <webElementGuid>3c462fe8-64a3-4472-990d-70f71dde1920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>69ff5cd2-bd4d-4b6b-b1e1-847f8c785f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
