<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enter the code from your emailEnter the_08da3e</name>
   <tag></tag>
   <elementGuidId>2c2b210a-fb72-4878-afc9-d3c0ef5169ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'fb_content clearfix ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4e99e96-b2be-48da-b242-57cf41aac620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fb_content clearfix </value>
      <webElementGuid>719f8b19-bc75-4278-a203-cc970314f352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>aff9788f-80b4-447a-8482-92fabc4380e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>16823104-a04f-48cc-86b6-586f231bac72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter the code from your emailEnter the code from your emailLet us know that this email address belongs to you. Enter the code from the email sent to ifs18063.elyta@gmail.com. FB- Please check the email that we sent and enter the 5-digit code.Send Email AgainUpdate Contact InfoContinue</value>
      <webElementGuid>3358bd4f-3003-469c-954d-970a53549f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)</value>
      <webElementGuid>3fff950a-9c15-4c5b-a124-1a87bc8b4563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='content']</value>
      <webElementGuid>c74ca020-94a8-4376-b5d0-b320fdaf7b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='globalContainer']/div</value>
      <webElementGuid>385bd14e-6247-4f38-a6bb-98c54b45100c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Settings'])[1]/following::div[2]</value>
      <webElementGuid>4552010b-d689-4948-b115-8ff42b0baaa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>c197940a-2ae5-4f49-a91a-d0aed90e87b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'content' and (text() = 'Enter the code from your emailEnter the code from your emailLet us know that this email address belongs to you. Enter the code from the email sent to ifs18063.elyta@gmail.com. FB- Please check the email that we sent and enter the 5-digit code.Send Email AgainUpdate Contact InfoContinue' or . = 'Enter the code from your emailEnter the code from your emailLet us know that this email address belongs to you. Enter the code from the email sent to ifs18063.elyta@gmail.com. FB- Please check the email that we sent and enter the 5-digit code.Send Email AgainUpdate Contact InfoContinue')]</value>
      <webElementGuid>a6c324c3-0e58-41ef-98c7-f8c0d4a22a98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
