<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_a-rg9l5f1hrvwe</name>
   <tag></tag>
   <elementGuidId>cb84652b-b7f6-45f4-9eae-55028a7fc778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-rg9l5f1hrvwe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-rg9l5f1hrvwe&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c890c3ba-30b0-455d-bff3-652576b9d558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>cee56a40-e05b-4e66-9266-2e06b1a18c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR&amp;co=aHR0cHM6Ly93d3cuZmJzYnguY29tOjQ0Mw..&amp;hl=en-GB&amp;v=Km9gKuG06He-isPsP6saG8cn&amp;theme=light&amp;size=normal&amp;cb=3d8lejitpw77</value>
      <webElementGuid>342e50e1-d969-4e4a-a5c7-f94251fbba6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>a6cd6737-e4de-4d5a-9d4f-f89c278b3f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>715a5279-5c61-400d-b6a6-ea6d86c716d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a024bb67-55a2-4093-95e7-7f9df54bc507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-rg9l5f1hrvwe</value>
      <webElementGuid>13bc1ef8-127d-4dfa-8874-f1c84ba85666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a94eae5-7bb5-4ecb-9eef-7bfad8ef5956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>587c2fdc-1746-4c27-90c3-32c3e24cb80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>e037010a-054a-4e5c-9560-63466ccc3cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;_7t5v chrome webkit win x1 Locale_en_GB&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>46f86110-80fc-48be-b35d-ed278a9e07a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Facebook/iframe_concat(Help us confirm that it, , s _890ae7</value>
      <webElementGuid>d830502f-5d55-4227-a0fa-ff2d8c416d25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-rg9l5f1hrvwe']</value>
      <webElementGuid>1e8f782c-d9d8-4360-b4d1-81bfb1e33493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1c66319c-69d5-4bc8-8ae3-8dd7c92bd5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR&amp;co=aHR0cHM6Ly93d3cuZmJzYnguY29tOjQ0Mw..&amp;hl=en-GB&amp;v=Km9gKuG06He-isPsP6saG8cn&amp;theme=light&amp;size=normal&amp;cb=3d8lejitpw77' and @name = 'a-rg9l5f1hrvwe']</value>
      <webElementGuid>34e27993-e01b-4295-b909-af5575fa2d5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
