<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_c-rg9l5f1hrvwe</name>
   <tag></tag>
   <elementGuidId>11152c76-976c-4c0c-a93e-2fee9680ca9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-rg9l5f1hrvwe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-rg9l5f1hrvwe&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dd9b27d1-587e-488f-8cc2-19f9f09c6fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>c1880e6a-b91e-44ac-b8e2-dbf2fabfca03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en-GB&amp;v=Km9gKuG06He-isPsP6saG8cn&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR</value>
      <webElementGuid>d719ef8a-aac5-4a0f-9177-99caeedc8566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-rg9l5f1hrvwe</value>
      <webElementGuid>608c7a5c-f412-4568-8ea2-9df909d284f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b42fb2fc-f2d7-4a56-a980-c8332a94acbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6cad961f-ace2-40c8-9b21-3e8c42ad2e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>1d80b0d5-1aef-4d68-835a-fbb7bfb54486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;_7t5v chrome webkit win x1 Locale_en_GB&quot;]/div[4]/div[4]/iframe[1]</value>
      <webElementGuid>c53fd95a-2d74-4a9e-a6a5-b7b082d052a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Facebook/iframe_concat(Help us confirm that it, , s _890ae7</value>
      <webElementGuid>57eba705-b9bb-466d-822c-301913301013</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-rg9l5f1hrvwe']</value>
      <webElementGuid>fbc93ce8-3dd3-4aab-91b0-fe8ba7705a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>0aaab17e-512d-4137-b323-455658167811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en-GB&amp;v=Km9gKuG06He-isPsP6saG8cn&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR' and @name = 'c-rg9l5f1hrvwe']</value>
      <webElementGuid>21507171-b675-4ef9-b942-5b7a386c464f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
