<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(Help us confirm that it, , s _890ae7</name>
   <tag></tag>
   <elementGuidId>ed687736-5034-49a0-b1ce-7092fecfac69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='captcha-recaptcha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#captcha-recaptcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>948e5267-99f2-4a80-ab2e-b05ab2066eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captcha-recaptcha</value>
      <webElementGuid>2afdc19b-f392-45db-8baf-031c34d5786a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>241.546875</value>
      <webElementGuid>11c2c55f-d415-4f0b-a12d-1c96ca4c00a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x76ihet xwmqs3e x112ta8 xxxdfa6</value>
      <webElementGuid>3ab625a3-e1fa-407e-948d-57b8aec21ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/common/referer_frame.php</value>
      <webElementGuid>3a1f7eab-aefd-446b-9bf9-d8ef23022edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c9ff7f65-ee7d-47d3-97ab-f8263e23c9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captcha-recaptcha&quot;)</value>
      <webElementGuid>ec5a523f-fafd-4682-a368-732dab22ebbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='captcha-recaptcha']</value>
      <webElementGuid>48801045-479d-4af8-b5fe-33a19acfe1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollview']/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/iframe</value>
      <webElementGuid>7f3b88df-ffa5-4106-aef4-91a64f06a6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5d718b7f-10b0-46dc-9a66-7713bf139301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'captcha-recaptcha' and @src = '/common/referer_frame.php']</value>
      <webElementGuid>c15f84d1-bd5a-4f42-a65e-bae64cc9fd85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
