<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bridges_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>90e4a5e4-1c37-4079-8e37-44b7bcd4cfab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c5db7c6e-93c6-4e72-815e-175ff0d0894a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>2a6a23b2-5a83-4bc0-b67a-f596c39aaaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AEkXODDI4Km5KLFpE8BHWT28Aa8PROP1XxsYGlwENc3-rSWVgk-d0NnuLSzSs8e7XdEzev93FGsHMy1ohIZo6O6bQwjkyPTigfIcLkaO6vifcN82Y8J-OGOUEQNRGfWMUeJxtbn89xCfkFjm9BeTpp5ojcX3MwP30bl4KRIDHck1K-GebSv6IZiYzrkZZzfyJMR7VdFSTRHie4f_5s5W7h6NqBD-_2Z0jA&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR</value>
      <webElementGuid>7ff3ae5f-6ace-4992-a3c0-a9bc07e955db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>cb1af4c7-b174-4766-a6c8-8b56c3d74c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Facebook/iframe_c-rg9l5f1hrvwe</value>
      <webElementGuid>750f95b7-32d6-4fc5-8d79-99b32d7e8e30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>b7ff10fe-9147-4bab-ac8e-5aed341bfaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AEkXODDI4Km5KLFpE8BHWT28Aa8PROP1XxsYGlwENc3-rSWVgk-d0NnuLSzSs8e7XdEzev93FGsHMy1ohIZo6O6bQwjkyPTigfIcLkaO6vifcN82Y8J-OGOUEQNRGfWMUeJxtbn89xCfkFjm9BeTpp5ojcX3MwP30bl4KRIDHck1K-GebSv6IZiYzrkZZzfyJMR7VdFSTRHie4f_5s5W7h6NqBD-_2Z0jA&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR')])[9]</value>
      <webElementGuid>32973744-744e-474b-90b4-264b55905a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>5fd35d22-178e-454c-9d4e-f605f37041b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AEkXODDI4Km5KLFpE8BHWT28Aa8PROP1XxsYGlwENc3-rSWVgk-d0NnuLSzSs8e7XdEzev93FGsHMy1ohIZo6O6bQwjkyPTigfIcLkaO6vifcN82Y8J-OGOUEQNRGfWMUeJxtbn89xCfkFjm9BeTpp5ojcX3MwP30bl4KRIDHck1K-GebSv6IZiYzrkZZzfyJMR7VdFSTRHie4f_5s5W7h6NqBD-_2Z0jA&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR']</value>
      <webElementGuid>ce51a97c-e4c9-4fd4-85a8-1a2ac7775823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
