<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bridges_rc-image-tile-33_1</name>
   <tag></tag>
   <elementGuidId>d837756b-0a63-4d75-b196-2a2df6585949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>626e08a7-e427-4ea7-b869-c7cb5fb1a234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>20192e6f-6a7e-4b6b-af48-ad69ca44c7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AEkXODDLzMq2ctxgIa7AXhLAVQY2z2ivfW-QiZ7ejqlUUUGHoT_Lb3SCXEC6c_n_wSElhfF9KpZ_1IPOwBUGz1qD2rpGQ9ZHDssia4Jz87ptsuns2UV7nMmhIe1hZsDyuUefY9S1tI-rChZyVoI9UqCEhXWvLBjGc1NtosCFdIlfAYvQuO77oRds0aaRGk8GUQnWj8rT5mOKCJXBxS7mit53EUoLEpV6mw&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR</value>
      <webElementGuid>202bee38-af5a-4f65-8481-8b84e64b156b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>36f2f892-61b4-4766-8dc8-194f2e0b33c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Facebook/iframe_c-rg9l5f1hrvwe</value>
      <webElementGuid>3a94754f-77b1-46f2-a47a-320335933905</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>dccf22f2-9b8d-4c17-974a-545bba2733fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AEkXODDLzMq2ctxgIa7AXhLAVQY2z2ivfW-QiZ7ejqlUUUGHoT_Lb3SCXEC6c_n_wSElhfF9KpZ_1IPOwBUGz1qD2rpGQ9ZHDssia4Jz87ptsuns2UV7nMmhIe1hZsDyuUefY9S1tI-rChZyVoI9UqCEhXWvLBjGc1NtosCFdIlfAYvQuO77oRds0aaRGk8GUQnWj8rT5mOKCJXBxS7mit53EUoLEpV6mw&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR')])[8]</value>
      <webElementGuid>458b1704-431f-44f0-bb1e-485364dbfe31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>50245c21-87a3-4637-8750-55d719970584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AEkXODDLzMq2ctxgIa7AXhLAVQY2z2ivfW-QiZ7ejqlUUUGHoT_Lb3SCXEC6c_n_wSElhfF9KpZ_1IPOwBUGz1qD2rpGQ9ZHDssia4Jz87ptsuns2UV7nMmhIe1hZsDyuUefY9S1tI-rChZyVoI9UqCEhXWvLBjGc1NtosCFdIlfAYvQuO77oRds0aaRGk8GUQnWj8rT5mOKCJXBxS7mit53EUoLEpV6mw&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR']</value>
      <webElementGuid>abb3ffee-4ad6-4524-81a8-86518a3fc984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
